from typing import Any

from . import core as _core
from .core import (
    _git_value,
    apply_event_view,
    build_record_replay_series,
    build_record_replay_site_metrics,
    build_record_replay_sites,
    build_record_replay_timeline_events,
    extract_policy_sources,
    is_pytest_command,
    load_record_replay_events,
    load_run_json,
    parse_pytest_failures,
    parse_pytest_summary,
    summarize_record_replay,
    utc_now_iso,
    write_report_html,
    write_run_json,
)
from .html_renderer import _normalize_chart_series, render_report_html


def build_run_record(
    *,
    command: list[str],
    returncode: int,
    started_at: str,
    ended_at: str,
    duration_ms: int,
    interceptor_path: str | None,
    ld_preload_effective: str,
    interceptor_active: bool,
    summary_override: dict[str, int] | None = None,
    run_json_path: str | None = None,
    additional_events: list[dict[str, Any]] | None = None,
    stdout_excerpt: str = "",
    stderr_excerpt: str = "",
    network_metrics: dict[str, Any] | None = None,
    network_series: dict[str, list[int]] | None = None,
    observed_sites: list[str] | None = None,
    site_metrics: dict[str, dict[str, Any]] | None = None,
    record_replay_path: str = "",
    policy_sources: list[dict[str, str]] | None = None,
    record_replay_mode: str | None = None,
    shm_name: str | None = None,
    shm_open_mode: str | None = None,
) -> dict[str, Any]:
    return _core.build_run_record(
        command=command,
        returncode=returncode,
        started_at=started_at,
        ended_at=ended_at,
        duration_ms=duration_ms,
        interceptor_path=interceptor_path,
        ld_preload_effective=ld_preload_effective,
        interceptor_active=interceptor_active,
        summary_override=summary_override,
        run_json_path=run_json_path,
        additional_events=additional_events,
        stdout_excerpt=stdout_excerpt,
        stderr_excerpt=stderr_excerpt,
        network_metrics=network_metrics,
        network_series=network_series,
        observed_sites=observed_sites,
        site_metrics=site_metrics,
        record_replay_path=record_replay_path,
        policy_sources=policy_sources,
        record_replay_mode=record_replay_mode,
        shm_name=shm_name,
        shm_open_mode=shm_open_mode,
    )


__all__ = [
    "_git_value",
    "apply_event_view",
    "build_record_replay_series",
    "build_record_replay_site_metrics",
    "build_record_replay_sites",
    "build_record_replay_timeline_events",
    "build_run_record",
    "extract_policy_sources",
    "is_pytest_command",
    "load_record_replay_events",
    "load_run_json",
    "parse_pytest_failures",
    "parse_pytest_summary",
    "render_report_html",
    "summarize_record_replay",
    "utc_now_iso",
    "write_report_html",
    "write_run_json",
    "_normalize_chart_series",
]
